set -g status on
set -g status-style bg=default,fg=#6e7781
set -g status-left ""
set -g status-right "#{session_name}"
set -g status-right-style bg=default,fg=#6e7781
set -g status-left-length 0
set -g status-right-length 20
set -g window-status-format " #W "
set -g window-status-current-format " #W "
set -g window-status-current-style bg=default,fg=#1b1f24
set -g window-status-style bg=default,fg=#8c8e90
set -g status-justify left
set -g window-status-separator ""

set -g pane-border-style fg=#f6f8fa
set -g pane-active-border-style fg=#d0d7de
